### ISSUE TITLE
Priorisation

### ISSUE THREAD

**Issue by n0rdlicht** [GispoCoding/gemeindescan-exporter#1]
Main goal being a first version to export a datapackage containing styled GeoJSON from QGIS.

High Priority
- Translate QGIS Simple, Graduated and Categorized Symbology to Simple Styles (Lines and Polygons) or Leaflet Stylings (Points: Circles)
- Configure Datapackage metadata: name, title, sources
- Configure Snapshot metadata: description, legend (visually based on QGIS symbology), bounds

Medium Priority
- Store/Manage/Load snapshot settings
- Configure Datapackage metadata: license, keywords, contributors, maintainers, custom fields (e.g. Datahub/Gemeindescan/... Specific Fields)

Low Priority
- UI polish
- Reconfigure Layerset of current snapshot
- Loading/Import of existing snapshots/datapackages
- Configure Snapshot metadata: attribution

**Comment by Joonalai** [comment]
Here are some additional notices:
* Polygons with centroid style could be exported as point layer

**Comment by n0rdlicht** [comment]
> Here are some additional notices:
> 
> * Polygons with centroid style could be exported as point layer

True, that would indeed make sense. 

On the same note: v0.0.1/0.0.2 seems to not yet differentiate between Simple Styles for Lines and Polygons (mediatype `application/geo+json`) and Points styled as Circles with Leaflet Styles (mediatype `application/vnd.simplestyle-extended`). Since we didn't implement that yet in the initial script: you think this is possible or would require some hours to add?

**Comment by Joonalai** [comment]
Can you @n0rdlicht provide a simple example file of a snapshot containing Circles with Leaflet Styles?

**Comment by n0rdlicht** [comment]
The sample includes a QGIS file and geojson layer (`point-sample.geojson`), as well as the expected json Data Package (`point-sample-snapshot.json`) and the intermediary styled GeoJSON (`point-sample-snapshot.geojson`). Let me know if you have questions.
[point-sample.zip](https://github.com/GispoCoding/gemeindescan-exporter/files/5274342/point-sample.zip)

**Comment by Joonalai** [comment]
@n0rdlicht based on the key mappings document, fill (bool), stroke (bool) and title (str) are not visible in the example snapshot. Should I ignore those for now?

**Comment by n0rdlicht** [comment]
> @n0rdlicht based on the key mappings document, fill (bool), stroke (bool) and title (str) are not visible in the example snapshot. Should I ignore those for now?

Title might need an interface in the future. For now I would not worry about it and leave it to the Snapshot author to set a title column on the layer for now. As for the bools: according to the leaflet documentation this is only required when it should not be drawn ([Leaflet Path](https://leafletjs.com/reference-1.7.1.html#path))

**Comment by Joonalai** [comment]
I will add the bools there as well to fully support the format.
